### ISSUE TITLE
givePermissons issue

### ISSUE THREAD

**Issue by VitaliyKh** [zlyfer/DiscordDynChanBot#1]
If settings - "givePermissions" or/and "giveChannelPermissions" is true - bot сreate channel, gives this  permission, but in next step he grant permission "Read Messages" ![image](https://user-images.githubusercontent.com/45329201/48977714-55d51500-f0a8-11e8-91c5-eec08dddb939.png) , what lead to losing first permissions. 

without lines 22-24 of index.js bot work normally

**Comment by zlyfer** [comment]
Temporarily used this hotfix until planned complete rewrite.
Thanks for the feedback!

Cheers.
